---
version: "3.8"

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    command:
      - --accesslog.fields.names.StartUTC=drop
      - --api=true
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`test.domaine.com`)
      - traefik.http.routers.api.entrypoints=web,websecure
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=leresolver
      - traefik.http.routers.api.middlewares=api-auth
      - traefik.http.middlewares.api-auth.basicauth.usersfile=/password/.htpasswd
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/yggnode/Config/traefik/traefik.toml:/traefik.toml:ro
      - /home/yggnode/Config/password/:/password:ro
      - /home/yggnode/Config/traefik/acme.json:/acme.json

networks:
  traefik_network:
    external: True